site_name: Chris Docs
docs_dir: docs-3
repo_name: 'multi_lang_test'
repo_url: 'https://github.com/ChrisChen2023/multi_lang_test'

edit_uri: 'https://github.com/ChrisChen2023/multi_lang_test/edit/master/docs-3'

theme:
  name: material
  icon:
      repo: fontawesome/brands/github
  logo: 'https://docs-cdn.nebula-graph.com.cn/figures/vesoft-nebula-logo-white22-12-21.png'
  favicon: 'https://docs-cdn.nebula-graph.com.cn/figures/favicon.ico'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: nebula
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
- NebulaGraph: en/index.md
- Cloud:
  - Section One: en/getting-started/topic-1.md
- GQL: en/about.md
- Visualization Tools:

plugins:
  - search
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
      - locale: en
        name: English
        build: true
        default: true
        site_name: "NebulaGraph manual"
        site_url: https://docs.nebula-graph.io/ # 社区版英文域名
        fixed_link: https://docs.nebula-graph.com.cn/
      - locale: zh
        name: 简体中文
        build: true
        site_name: "NebulaGraph 用户手册"
        site_url: https://docs.nebula-graph.com.cn/  # 社区版中文域名
        fixed_link: https://docs.nebula-graph.io/
          
extra: 
  version:
    provider: mike

