site_name: Chris Docs
docs_dir: docs-3
repo_name: 'multi_lang_test'
repo_url: https://github.com/ChrisChen2023/multi_lang_test
site_url: https://chrischen2023.github.io/multi_lang_test/
copyright: >
  Copyright &copy; 2018 - 2023 NebulaGraph -
  <a href="#__consent">Change cookie settings</a>

edit_uri: 'https://github.com/ChrisChen2023/multi_lang_test/edit/main/docs-3'

theme:
  name: material
  custom_dir: docs-3/overrides
  font:
    code: Source Code Pro
    text: Noto Sans
  icon:
      repo: fontawesome/brands/github
  logo: 'https://docs-cdn.nebula-graph.com.cn/figures/vesoft-nebula-logo-white22-12-21.png'
  favicon: 'https://docs-cdn.nebula-graph.com.cn/figures/favicon.ico'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - announce.dismiss
  palette:
    - scheme: nebula
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/note.css
  - stylesheets/hide_version_selector.css
  - stylesheets/extra.css
  
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      separator: "_"
#   toc_depth: 1
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs-3/reuse/

nav:
  - Home: README.md
  - Introduction:
      - What is NebulaGraph: 1.introduction/1.what-is-nebula-graph.md
      - Data model: 1.introduction/2.data-model.md
      - Path: 1.introduction/2.1.path.md
      - VID: 1.introduction/3.vid.md
      - NebulaGraph architecture:
        - Architecture overview: 1.introduction/3.nebula-graph-architecture/1.architecture-overview.md
        - Meta Service: 1.introduction/3.nebula-graph-architecture/2.meta-service.md
        - Graph Service: 1.introduction/3.nebula-graph-architecture/3.graph-service.md
        - Storage Service:  1.introduction/3.nebula-graph-architecture/4.storage-service.md
  
  - Quick start:
      - Deploy NebulaGraph using Docker: 2.quick-start/1.quick-start-workflow0.md
      - Deploy NebulaGraph on-premise: 
        - Step 1 Install NebulaGraph: 2.quick-start/2.install-nebula-graph.md
        - Step 2 Manage NebulaGraph Service: 2.quick-start/5.start-stop-service.md
        - Step 3 Connect to NebulaGraph: 2.quick-start/3.connect-to-nebula-graph.md
        - Step 4 Register the Storage Service: 2.quick-start/3.1add-storage-hosts.md
        - Step 5 Use nGQL (CRUD): 2.quick-start/4.nebula-graph-crud.md
      - nGQL cheatsheet: 2.quick-start/6.cheatsheet-for-ngql.md

  - nGQL guide:
      - nGQL overview:
        - Overview: 3.ngql-guide/1.nGQL-overview/1.overview.md
        - Graph patterns: 3.ngql-guide/1.nGQL-overview/3.graph-patterns.md
        - Comments: 3.ngql-guide/1.nGQL-overview/comments.md
        - Identifier case sensitivity: 3.ngql-guide/1.nGQL-overview/identifier-case-sensitivity.md
        - Keywords: 3.ngql-guide/1.nGQL-overview/keywords-and-reserved-words.md
        - nGQL style guide: 3.ngql-guide/1.nGQL-overview/ngql-style-guide.md

  - Dashboard (Community):
      - What is NebulaGraph Dashboard: nebula-dashboard/1.what-is-dashboard.md
      - Deploy Dashboard: nebula-dashboard/2.deploy-dashboard.md
      - Connect to Dashboard: nebula-dashboard/3.connect-dashboard.md
      - Use Dashboard: nebula-dashboard/4.use-dashboard.md
      - Monitoring metrics: nebula-dashboard/6.monitor-parameter.md


          
extra: 
  version:
    provider: mike
  analytics:
    provider: google
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-excited-outline
          name: The content was excellent and thoroughly answered my questions.
          data: 5
          note: >-
            Thanks for your feedback! 
        - icon: material/emoticon-happy-outline
          name: The content was useful and answered most of my questions. 
          data: 4
          note: >-
            Thanks for your feedback! Help us improve this page by
            submitting a <a href="https://github.com/ChrisChen2023/multi_lang_test/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub issue</a>.
        - icon: material/emoticon-neutral-outline
          name: The content was adequate and provided the basic information I needed.
          data: 3
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting a <a href="https://github.com/ChrisChen2023/multi_lang_test/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub issue</a>.
        - icon: material/emoticon-frown-outline
          name: The content provided some information, but it did not fully answer my questions.
          data: 2
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting a <a href="https://github.com/ChrisChen2023/multi_lang_test/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub issue</a>.
        - icon: material/emoticon-sad-outline
          name: The content did not provide the information I was looking for or lacked clarity.
          data: 1
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting a <a href="https://github.com/ChrisChen2023/multi_lang_test/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">GitHub issue</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      github:
        name: GitHub
        checked: true
      analytics:
        name: Google Analytics
        checked: true  
    actions:
      - accept
      - manage
      - reject
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/vesoft-inc/nebula-docs-cn'
# nav.comm.end
  nebula:
    release: 3.6.0
    nightly: nightly
    master: master
    branch: release-3.6
    tag: v3.6.0
    name: NebulaGraph 
  dockercompose:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
  console:
    release: 3.5.0
    branch: release-3.5
    tag: v3.5.0 
  dashboard:
    release: 3.4.0
    tag: v3.4.0
    base100: 1.0.0
    branch: release-3.4   

plugins:
  - search
  - macros:
      include_dir: docs-3/reuse/

